### ISSUE TITLE
Struggling to get this to work.

### ISSUE THREAD

**Issue by izakfilmalter** [mikaelvesavuori/figmagic#1]
Hey,

Thanks for taking the time to build this, it's exactly what I need.

```
izak-mbp:client izakfilmalter$ yarn figmagic
yarn run v1.6.0
(node:13892) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ yarn figmagic:clean && yarn run figmagic:saveFromApi && yarn figmagic:build && yarn figmagic:getImages && yarn figmagic:downloadImages
(node:13894) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ rm -rf specs/ && rm -rf tokens/ && rm -rf figma
(node:13899) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ mkdir -p figma && wget 'https://api.figma.com/v1/files/{removed}' --header='X-Figma-Token: {removed}' -O figma/figma.json
--2018-04-26 10:21:44--  https://api.figma.com/v1/files/{removed}
Resolving api.figma.com (api.figma.com)... 52.88.194.44
Connecting to api.figma.com (api.figma.com)|52.88.194.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘figma/figma.json’

figma/figma.json                           [  <=>                                                                     ] 270.86K  1.15MB/s    in 0.2s    

2018-04-26 10:21:45 (1.15 MB/s) - ‘figma/figma.json’ saved [277358]

(node:13903) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ node $npm_package_config_figmagicPath/bin/index.js
/Users/izakfilmalter/Projects/Simspace/portal/client/node_modules/figmagic/bin/index.js:28
	const designTokens = designtokensPage.children;
	                                      ^

TypeError: Cannot read property 'children' of undefined
    at createTokens (/Users/izakfilmalter/Projects/Simspace/portal/client/node_modules/figmagic/bin/index.js:28:40)
    at Object.<anonymous> (/Users/izakfilmalter/Projects/Simspace/portal/client/node_modules/figmagic/bin/index.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried this with both node v8.11.1 and v10.0.0. Am I missing something?

**Comment by mikaelvesavuori** [comment]
Hi Izak, happy to hear this is something you want to use!

I've done some preliminary looking into this. First and foremost it seems as if the Figma page which should be called "Design Tokens" is either missing or has no frames inside of it. I tried to replicate this error in a few ways but didn't get exactly the one you have.

Could you please begin by making sure that your document follows the format as in the image below? Project at [https://www.figma.com/file/KLLDK9CBSg7eAayiTY3kVqC8/Figmagic-Design-System-Example](https://www.figma.com/file/KLLDK9CBSg7eAayiTY3kVqC8/Figmagic-Design-System-Example).
<img width="1680" alt="figma-document-structure" src="https://user-images.githubusercontent.com/23580994/39321512-8c682a30-4987-11e8-9489-9452fc52f3a8.png">

There is currently very little error-handling or fail-safing if the document structure is "incorrect", but it's certainly something I am going to put some more time into. That, and perhaps updating the readme with more explicit instructions as I get more input into what works or not.

**Comment by mikaelvesavuori** [comment]
Closing this for inactivity and changes in the code since this surfaced.
